config/routes.rb
Rails.application.routes.draw do
  get 'user/new'

  root 'static_pages#home'
  
  get 'about' => 'static_pages#about'

  get 'help' => 'static_pages#help'
  
  get 'contact' => 'static_pages#contact'
  
  get 'log_in' => 'static_pages#log_in'
  
  get 'sign_up' => 'user#sign_up'

end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@ [a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 6 }

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
  
  def contact
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title='')
  base_title="Social Network"
    if page_title.empty?
      base_title
    else
      "#{page_title}|#{base_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Social Network
    by <a href="http://wwww.facebook.com/groups/rubyonrailsbonevet">Ruby on Rails group</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://www.bonevet.org/blog/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Social Network", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path  %></li>
        <li><%= link_to "Login", log_in_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<img src="http://rubyonrails.org/images/rails-logo.svg" class="foto"></img>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render'layouts/header'%>

    
    <div class="container">
      <%= yield %>
      <%= render 'layouts/shim'%>
      <%= render'layouts/footer'%>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
    <head>
         <title><%= yield(:title) %>|Social Network</title>
    </head>
    <body>
      <div class="center jumbotron">   
        <h1>About</h1>
        <p>
           This web is a mini website were building at <a href="http://www.bonevet.org/blog/">Bonevet</a> in the course of <a href="https://www.facebook.com/groups/rubyonrailsbonevet">Ruby on Rails</a>
        </p>
      </div>
    </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<!DOCTYPE html>
<html>
    <head>
         <title><%= yield(:title) %>|Social Network</title>
    </head>
    <body>
      <div class="center jumbotron">
        <h1>Contact</h1>
        <p>To contact us you can go to this group <a href="https://www.facebook.com/groups/rubyonrailsbonevet">Bonevet</a>
            or you can contact me personaly with <a href="https://www.facebook.com/ajriii">Ajri Sylhasi</a>. :)
        </p>
      </div>
    </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<!DOCTYPE html>
<html>
    <head>
         <title><%= yield(:title) %>|Social Network</title>
    </head>
    <body>
      <div class="center jumbotron">    
        <h1>HELP</h1>
        <p>
            If you need help regarding this course please contact the "Professionals" on
            <a href="https://www.facebook.com/groups/rubyonrailsbonevet/">Facebook.</a>
        </p>
      </div>
    </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
    <head>
         <title><%= yield(:title) %>|Social Network</title>
    </head>
    <body>
      <div class="center jumbotron">
        <h1>THE MOST AWESOME SOCIAL NETWORK IN THE PLANET</h1>
        <h2>
            This is the social network we are creating in the course of RoR at
            <a href="http://www.bonevet.org/">BONEVET.</a>
        </h2>
        <%=link_to "Sign up now!", sign_up_path, class: "btn btn-lg btn-primary" %>
      </div>
    </body>
</html>

app/views/static_pages/log_in.html.erb
<% provide(:title, "Log In") %>
<!DOCTYPE html>
<html>
    <head>
         <title><%= yield(:title) %>|Social Network</title>
    </head>
    <body>
      <div class="center jumbotron">    
        <h1>Log In</h1>
        <p>
            At the moment this part is under construction . Sorry for the inconvenience .
        </p>
      </div>
    </body>
</html>

app/views/user/sign_up.html.erb
<% provide(:title, "Sign Up") %>
<!DOCTYPE html>
<html>
    <head>
         <title><%= yield(:title) %>|Social Network</title>
    </head>
    <body>
      <div class="center jumbotron">    
        <h1>Sign Up</h1>
        <p>
            At the moment this part is under construction . Sorry for the inconvenience .
        </p>
      </div>
    </body>
</html>